version = 0.1

[default.deploy.parameters]
stack_name = "goguru-api"
resolve_s3 = true
s3_prefix = "goguru-api"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "AllowedOrigin=\"https://goguru.dev\""
image_repositories = ["GoExecutorFunction=060795906686.dkr.ecr.us-east-1.amazonaws.com/goguruapic2f2e8e4/goexecutorfunction7f0191ccrepo"]

[default.global.parameters]
region = "us-east-1"
